# Site settings
title: Riccardo Ali
email: rma55@cam.ac.uk
description: Academic webpage of Riccardo Ali
baseurl: ""
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
    Riccardo Ali<br/>
    Department of Computer Science<br/>
    University of Cambridge

location: >
  Computer Laboratory<br/>
  15 JJ Thomson Ave<br/>
  Cambridge CB3 0FD

contact: >
    <a href="mailto:rma55@cam.ac.uk" target="_blank"><i class="fa fa-envelope fa-1x"></i> Email</a> <br/>
    <a href="https://www.linkedin.com/in/riccardo-ali/"><i class="fa fa-linkedin-square fa-1x"></i>  LinkedIn</a>

# Pages shown in navbar
nav_pages:
#  - name: about
#  - name: publications
#  - name: awards
#  - name: research
#  - name: software
#  - name: team
#  - name: teaching

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Doe
  first_name: [John]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
